services:
  - type: web
    name: etx-modular-pipeline
    env: python
    plan: free
    buildCommand: "pip install -r requirements-prod.txt"
    startCommand: gunicorn app.app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false